### ISSUE TITLE
Създадох този issue, защото не знаех как да се свържа с теб

### ISSUE THREAD

**Issue by NikolaTotev** [MitkoDyakov/GameBug#1]
Здравей! 
Знам че не е най-подходящия начин за комуникация, но само този канал намерих.
Твоя gamepad го видях на сайта на Hackster.io и се зарадвах като видях, че човека е българин!

Аз също си падам по електроника/роботика, и от дълго време търся други хора, които имат същите интереси.
Много бих се радвал ако може да си разменим някакви координати. За мен всичко работи, дискорд, фб, имейл и тн.

Поздрави,
Никола

**Comment by MitkoDyakov** [comment]
Здравей Никола!

Разбира се ще се радвам да разменим контакти! Може да ми пратиш един мейл на dimitar ат xtech.bg

Поздрави,
Митко
